#!/usr/bin/env bash

# Determine command to run java
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Determine java options
if [ -n "$GRAIN_OPTS" ]
   then
     GRAIN_OPTS="$GRAILS_OPTS"
   else
     GRAIN_OPTS="-server -Xmx256M -Xms32M -XX:PermSize=32m -XX:MaxPermSize=128m -Dfile.encoding=UTF-8"
  fi
JAVA_OPTS="$GRAIN_OPTS $JAVA_OPTS"

# Get target Grain version
VERSION_REGEX="grain\.version\s*=\s*(.+)"
APP_PROPS="application.properties"

if [ ! -f $APP_PROPS ]; then
    echo "Error: application.propoerties not found";
    exit 1;
fi

while read line; do
    if [[ $line =~ $VERSION_REGEX ]]; then
        GRAIN_VERSION="${BASH_REMATCH[1]}"
    fi
done < $APP_PROPS

# Check if site deps exists for current Grain version
SITE_DEPS=".site-${GRAIN_VERSION}.dep"

if [ ! -f $SITE_DEPS ]; then
    # Site deps don't exist - generate them
    ./gradlew gendeps
    if [ $? -ne 0 ]; then
       exit 1;
    fi
fi

# Get Grain JAR from site deps
read -r GRAIN_JAR < $SITE_DEPS

if [ ! -f $GRAIN_JAR ]; then
    # Grain Jar doesn't exist - regenerate site deps and recompute Grain Jar
    ./gradlew gendeps
    if [ $? -ne 0 ]; then
       exit 1;
    fi
    read -r GRAIN_JAR < $SITE_DEPS
fi

# Check if site deps are valid
exec "$JAVACMD" $JAVA_OPTS -cp $GRAIN_JAR com.sysgears.grain.SiteLauncher $GRAIN_VERSION -- "$@"
if [ $? -eq 2 ]; then
    # Site deps invalid - regenerate them
    ./gradlew gendeps
    if [ $? -ne 0 ]; then
       exit 1;
    fi
    exec "$JAVACMD" $JAVA_OPTS -cp $GRAIN_JAR com.sysgears.grain.SiteLauncher $GRAIN_VERSION -- "$@"
fi

